// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsSATesbrp9Ghk7MZvVvZnzfBV5-Rm4A4',
    appId: '1:69945311688:web:c9df5f1ce1519d11b140fd',
    messagingSenderId: '69945311688',
    projectId: 'mobile-modul-6-85d75',
    authDomain: 'mobile-modul-6-85d75.firebaseapp.com',
    storageBucket: 'mobile-modul-6-85d75.firebasestorage.app',
    measurementId: 'G-81TCJNZJLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBznfIp7QjTBbKKEPH1Qiq_kQchrsoZVmY',
    appId: '1:69945311688:android:e4019f2224bd174cb140fd',
    messagingSenderId: '69945311688',
    projectId: 'mobile-modul-6-85d75',
    storageBucket: 'mobile-modul-6-85d75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ-_KfuJ_vi0KXPdEzBNGQL0WSL78fqOM',
    appId: '1:69945311688:ios:dae8648bb5a4bc29b140fd',
    messagingSenderId: '69945311688',
    projectId: 'mobile-modul-6-85d75',
    storageBucket: 'mobile-modul-6-85d75.firebasestorage.app',
    iosBundleId: 'com.example.demo3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ-_KfuJ_vi0KXPdEzBNGQL0WSL78fqOM',
    appId: '1:69945311688:ios:dae8648bb5a4bc29b140fd',
    messagingSenderId: '69945311688',
    projectId: 'mobile-modul-6-85d75',
    storageBucket: 'mobile-modul-6-85d75.firebasestorage.app',
    iosBundleId: 'com.example.demo3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsSATesbrp9Ghk7MZvVvZnzfBV5-Rm4A4',
    appId: '1:69945311688:web:b45bf4d9803ac6c9b140fd',
    messagingSenderId: '69945311688',
    projectId: 'mobile-modul-6-85d75',
    authDomain: 'mobile-modul-6-85d75.firebaseapp.com',
    storageBucket: 'mobile-modul-6-85d75.firebasestorage.app',
    measurementId: 'G-431R74BXRX',
  );
}
